import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import Navbar from "@/components/Navbar";
import Hero from "@/components/Hero";
import About from "@/components/About";
import Skills from "@/components/Skills";
import Projects from "@/components/Projects";
import Contact from "@/components/Contact";
import NavBar1 from "@/components/NavBar1";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
        <link
          href="https://fonts.googleapis.com/css2?family=Anton&family=Phudu&family=Prompt:wght@300&family=Teko&display=swap"
          rel="stylesheet"
        />
      </Head>
      <main className="snap-mandatory h-screen w-full  snap-y overflow-scroll overflow-x-hidden">
        <NavBar1 />

        <Hero id="home " className="snap-center" />

        <About id="about" className="snap-center" />

        <Skills id="skills" className="snap-center" />

        <Projects id="projects" className="snap-center" />

        <Contact id="contact" className="snap-center " />
      </main>
    </>
  );
}
